import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

class FirebaseSeeder {
  static Future<void> seedDatabase() async {
    final FirebaseFirestore firestore = FirebaseFirestore.instance;
    debugPrint('Iniciando inserción de aventuras...');

    final List<Map<String, dynamic>> soloAdventures = [
      {"number": 1, "type": "solo", "title": "Meditación matutina en la Laguna Alalay", "emoji": "🧘", "category": "Naturaleza", "locName": "Laguna Alalay", "description": "Empieza el día en paz, rodeado de agua y aves.", "challenge": "Mantener los ojos cerrados por 5 minutos escuchando la naturaleza.", "tips": "Lleva algo para sentarte.", "estimatedTime": "1 hora", "xpBase": 40, "costLevel": 1, "ubGeo": const GeoPoint(-17.4128, -66.1360)},
      {"number": 2, "type": "solo", "title": "Ruta de cafés de especialidad", "emoji": "☕", "category": "Gastronomía", "locName": "Recoleta", "description": "Conoce los mejores cafés de origen boliviano por tu cuenta.", "challenge": "Preguntar al barista por el proceso de tostado.", "tips": "Pide un V60 para apreciar los sabores.", "estimatedTime": "2 horas", "xpBase": 60, "costLevel": 2, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 3, "type": "solo", "title": "Lectura en la Plaza Colón", "emoji": "📖", "category": "Urbanos", "locName": "Plazuela Colón", "description": "Lleva tu libro favorito y lee en un banco bajo los árboles.", "challenge": "Terminar al menos un capítulo sin mirar el celular.", "tips": "Las tardes son más frescas y agradables.", "estimatedTime": "1.5 horas", "xpBase": 30, "costLevel": 1, "ubGeo": const GeoPoint(-17.3790, -66.1530)},
      {"number": 4, "type": "solo", "title": "Visita solo al Museo Arqueológico", "emoji": "🏺", "category": "Cultura", "locName": "Museo Arqueológico", "description": "Descubre la historia milenaria del valle a tu propio ritmo.", "challenge": "Encontrar la pieza más antigua del museo.", "tips": "Tienen piezas increíbles de la cultura Tiwanaku.", "estimatedTime": "1.5 horas", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3740, -66.1550)},
      {"number": 5, "type": "solo", "title": "Subida runner al Cristo de la Concordia", "emoji": "🏃", "category": "Aventura", "locName": "Cristo de la Concordia", "description": "Sube los escalones haciendo ejercicio y disfruta la vista.", "challenge": "Subir sin detenerte más de 2 veces.", "tips": "Lleva mucha agua.", "estimatedTime": "1.5 horas", "xpBase": 70, "costLevel": 1, "ubGeo": const GeoPoint(-17.38414, -66.13553)},
      {"number": 6, "type": "solo", "title": "Comida callejera en La Cancha", "emoji": "🥟", "category": "Gastronomía", "locName": "Mercado La Cancha", "description": "Atrévete a probar salteñas y jugos de la zona más comercial.", "challenge": "Pedir y comer algo que nunca hayas probado.", "tips": "Cuidado con tus pertenencias.", "estimatedTime": "1 hora", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3900, -66.1600)},
      {"number": 7, "type": "solo", "title": "Fotografía urbana en el pasaje San Rafael", "emoji": "📸", "category": "Arte", "locName": "Calle España", "description": "Captura los detalles coloniales que nadie nota.", "challenge": "Tomar 10 fotos de puertas y ventanas antiguas.", "tips": "La luz de la mañana es perfecta.", "estimatedTime": "1 hora", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3740, -66.1560)},
      {"number": 8, "type": "solo", "title": "Tarde de spa casero y relajación", "emoji": "🛁", "category": "En Casa", "locName": "Hogar", "description": "Date un baño relajante, pon música y desconecta del mundo.", "challenge": "Dejar el celular en otra habitación por 2 horas.", "tips": "Usa sales de epsom o aceites esenciales.", "estimatedTime": "2 horas", "xpBase": 40, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 9, "type": "solo", "title": "Aprender a cocinar un plato nuevo", "emoji": "👨‍🍳", "category": "En Casa", "locName": "Hogar", "description": "Busca una receta en YouTube y anímate a prepararla tú solo.", "challenge": "Cocinar algo que nunca hayas hecho antes.", "tips": "Lee toda la receta antes de empezar.", "estimatedTime": "2 horas", "xpBase": 70, "costLevel": 2, "ubGeo": const GeoPoint(0, 0)},
      {"number": 10, "type": "solo", "title": "Caminata introspectiva en Incachaca", "emoji": "🏞️", "category": "Aventura", "locName": "Incachaca", "description": "Conéctate contigo mismo caminando entre cascadas y naturaleza.", "challenge": "Caminar 15 minutos en total silencio.", "tips": "Zapatos antiderrapantes obligatorios.", "estimatedTime": "Medio día", "xpBase": 120, "costLevel": 2, "ubGeo": const GeoPoint(-17.4500, -66.1900)},
      {"number": 11, "type": "solo", "title": "Paseo en bicicleta por el Tunari", "emoji": "🚴", "category": "Aventura", "locName": "Parque Tunari", "description": "Pedalea por los senderos bajos del parque nacional.", "challenge": "Hacer una ruta de más de 5km.", "tips": "Lleva reparación de emergencia.", "estimatedTime": "3 horas", "xpBase": 100, "costLevel": 1, "ubGeo": const GeoPoint(-17.3500, -66.1200)},
      {"number": 12, "type": "solo", "title": "Tarde de dibujo o pintura", "emoji": "🎨", "category": "Arte", "locName": "Hogar / Parque", "description": "Expresa tu creatividad en un lienzo o cuaderno.", "challenge": "Dibujar lo que tienes frente a ti sin borrar.", "tips": "No busques perfección, busca expresión.", "estimatedTime": "2 horas", "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 13, "type": "solo", "title": "Visita al Convento Santa Teresa", "emoji": "⛪", "category": "Cultura", "locName": "Centro Histórico", "description": "Recorre este museo en silencio y absorbe la historia.", "challenge": "Escribir tu reflexión al salir.", "tips": "Se requiere respeto y silencio.", "estimatedTime": "1.5 horas", "xpBase": 50, "costLevel": 2, "ubGeo": const GeoPoint(-17.3730, -66.1570)},
      {"number": 14, "type": "solo", "title": "Cine solo y palomitas", "emoji": "🎬", "category": "Urbanos", "locName": "Cine Center / Multicine", "description": "Ve la película que tú quieres ver, sin llegar a acuerdos.", "challenge": "Ir a la función menos concurrida.", "tips": "Disfruta la paz de ir al cine solo.", "estimatedTime": "3 horas", "xpBase": 60, "costLevel": 2, "ubGeo": const GeoPoint(-17.3830, -66.1490)},
      {"number": 15, "type": "solo", "title": "Maratón de lectura en un café", "emoji": "📚", "category": "En Casa", "locName": "Café Local", "description": "Lleva tu libro y pide un café infinito.", "challenge": "Leer 50 páginas seguidas.", "tips": "Apaga el wifi del celular.", "estimatedTime": "3 horas", "xpBase": 70, "costLevel": 2, "ubGeo": const GeoPoint(-17.3860, -66.1480)},
      {"number": 16, "type": "solo", "title": "Explorar el Palacio Portales", "emoji": "🏰", "category": "Cultura", "locName": "Palacio Portales", "description": "Maravíllate con la arquitectura y los jardines.", "challenge": "Contar las estatuas del jardín.", "tips": "Revisa horarios de visita.", "estimatedTime": "1.5 horas", "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3830, -66.1490)},
      {"number": 17, "type": "solo", "title": "Caminata al mirador de Apote", "emoji": "🥾", "category": "Aventura", "locName": "Apote", "description": "Llega al mirador y disfruta de la soledad con vista al valle.", "challenge": "Gritar tu meta más grande al vacío.", "tips": "Lleva 2 litros de agua.", "estimatedTime": "4 horas", "xpBase": 120, "costLevel": 1, "ubGeo": const GeoPoint(-17.3300, -66.2000)},
      {"number": 18, "type": "solo", "title": "Ordenar tu habitación y mente", "emoji": "🧹", "category": "En Casa", "locName": "Hogar", "description": "El orden externo genera orden interno. Limpia tu espacio.", "challenge": "Tirar o donar 5 cosas que ya no uses.", "tips": "Pon música animada mientras lo haces.", "estimatedTime": "2 horas", "xpBase": 40, "costLevel": 0, "ubGeo": const GeoPoint(0, 0)},
      {"number": 19, "type": "solo", "title": "Probar un helado exótico", "emoji": "🍨", "category": "Gastronomía", "locName": "Recoleta", "description": "Date un gusto con un sabor raro de helado.", "challenge": "Pedir el sabor más raro del menú.", "tips": "Achachairú o lúcuma son buenos empiezos.", "estimatedTime": "30 min", "xpBase": 30, "costLevel": 1, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 20, "type": "solo", "title": "Tarde de escritura en plazuela", "emoji": "✍️", "category": "Arte", "locName": "Plazuela Colón", "description": "Escribe poemas, pensamientos o tu diario en un banco.", "challenge": "Escribir una carta a tu yo del futuro.", "tips": "Lleva un cuaderno bonito.", "estimatedTime": "1.5 horas", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3790, -66.1530)},
      {"number": 21, "type": "solo", "title": "Clase de Yoga en parque", "emoji": "🧘‍♂️", "category": "Naturaleza", "locName": "Parque Mariscal Santa Cruz", "description": "Haz tu rutina de yoga sobre el pasto.", "challenge": "Mantener una postura difícil por 30 seg.", "tips": "Lleva tu propia esterilla.", "estimatedTime": "1 hora", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3830, -66.1500)},
      {"number": 22, "type": "solo", "title": "Escuchar un podcast caminando", "emoji": "🎧", "category": "Urbanos", "locName": "El Prado", "description": "Camina por el Prado escuchando algo inspirador.", "challenge": "Caminar sin rumbo fijo por 1 hora.", "tips": "Mantén alerta al cruzar calles.", "estimatedTime": "1.5 horas", "xpBase": 40, "costLevel": 1, "ubGeo": const GeoPoint(-17.3790, -66.1520)},
      {"number": 23, "type": "solo", "title": "Comprar un libro y empezar a leerlo", "emoji": "📕", "category": "Urbanos", "locName": "Librería Local", "description": "Ve a una librería, elige con calma y empieza a leerlo ahí.", "challenge": "No salir sin un libro nuevo.", "tips": "Los libros de autores locales son geniales.", "estimatedTime": "2 horas", "xpBase": 60, "costLevel": 2, "ubGeo": const GeoPoint(-17.3754, -66.1523)},
      {"number": 24, "type": "solo", "title": "Tarde de siesta reparadora", "emoji": "😴", "category": "En Casa", "locName": "Hogar", "description": "Descansa sin culpa. Tu cuerpo lo necesita.", "challenge": "Apagar la alarma y dormir lo que el cuerpo pida.", "tips": "Oscuridad y silencio son clave.", "estimatedTime": "2 horas", "xpBase": 20, "costLevel": 0, "ubGeo": const GeoPoint(0, 0)},
      {"number": 25, "type": "solo", "title": "Desayuno buffet solo", "emoji": "🥞", "category": "Gastronomía", "locName": "Hotel Cala Cala", "description": "Date un lujo y desayuna como rey tú solo.", "challenge": "No mirar el celular durante el desayuno.", "tips": "Disfruta la soledad como un lujo.", "estimatedTime": "1.5 horas", "xpBase": 70, "costLevel": 3, "ubGeo": const GeoPoint(-17.3900, -66.1410)},
      {"number": 26, "type": "solo", "title": "Aprender 5 palabras en quechua", "emoji": "🗣️", "category": "Cultura", "locName": "Mercado / Calle", "description": "Pregúntale a una señora del mercado cómo se dicen 5 cosas.", "challenge": "Usar una de esas palabras en la siguiente compra.", "tips": "La gente valora el interés por su idioma.", "estimatedTime": "1 hora", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3900, -66.1600)},
      {"number": 27, "type": "solo", "title": "Ir al estadio a ver un partido", "emoji": "⚽", "category": "Aventura", "locName": "Estadio Félix Capriles", "description": "Vive la pasión del fútbol cochabambino con la hinchada.", "challenge": "Gritar un gol (o sufrir un gol en silencio).", "tips": "Cuidado con las opciones populares.", "estimatedTime": "3 horas", "xpBase": 80, "costLevel": 1, "ubGeo": const GeoPoint(-17.3820, -66.1480)},
      {"number": 28, "type": "solo", "title": "Cocinar una cena gourmet para 1", "emoji": "🍷", "category": "En Casa", "locName": "Hogar", "description": "Prepárate tu plato favorito de restaurante en casa.", "challenge": "Emplatarlo como en un chef.", "tips": "Pon música y sírvete vino.", "estimatedTime": "2 horas", "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(0, 0)},
      {"number": 29, "type": "solo", "title": "Hacer un regalo para alguien", "emoji": "🎁", "category": "Arte", "locName": "Hogar", "description": "Haz algo artesanal (una carta, un dibujo, algo cocinado) para alguien quieras.", "challenge": "Entregárselo en persona mañana.", "tips": "Los regalos hechos a mano tienen más valor.", "estimatedTime": "2 horas", "xpBase": 70, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 30, "type": "solo", "title": "Cena de paz en la Angostura", "emoji": "🌌", "category": "Especiales", "locName": "Laguna La Angostura", "description": "Ve solo con un sándwich y mira las estrellas.", "challenge": "Encontrar la constelación de Orión.", "tips": "Lleva abrigo, de noche hace frío.", "estimatedTime": "2 horas", "xpBase": 90, "costLevel": 1, "ubGeo": const GeoPoint(-17.4100, -66.2500)},
    ];

    final List<Map<String, dynamic>> coupleAdventures = [
      {"number": 31, "type": "pareja", "title": "Subida al Cristo de la Concordia al atardecer", "emoji": "✝️", "category": "Miradores", "locName": "Cristo de la Concordia", "description": "Sube los escalones o toma el teleférico para ver caer el sol sobre la ciudad.", "challenge": "Tomarse una foto abrazando la ciudad al fondo.", "tips": "Lleva una chompa, a esa hora refresca.", "estimatedTime": "1-2 horas", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.38414, -66.13553)},
      {"number": 32, "type": "pareja", "title": "Paseo romántico en la Laguna Alalay", "emoji": "🦆", "category": "Naturaleza", "locName": "Laguna Alalay", "description": "Una caminata tranquila rodeando la laguna, ideal para conversar y disfrutar de la brisa.", "challenge": "Comprar algo de comer a los patos y peces del lago.", "tips": "Evita las horas de sol más fuerte (12:00 - 15:00).", "estimatedTime": "1 hora", "xpBase": 40, "costLevel": 1, "ubGeo": const GeoPoint(-17.4128, -66.1360)},
      {"number": 33, "type": "pareja", "title": "Desayuno con salteñas en la Av. Pando", "emoji": "🥟", "category": "Gastronomía", "locName": "Avenida Pando", "description": "Empieza el día con el sabor más tradicional de la ciudad.", "challenge": "Comer la salteña sin que se caiga una gota de jugo.", "tips": "Las salteñas se acaban temprano, ve antes de las 10:00 AM.", "estimatedTime": "45 min", "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3754, -66.1523)},
      {"number": 34, "type": "pareja", "title": "Caminata por la Plaza Colón de noche", "emoji": "🌙", "category": "Urbanos", "locName": "Plazuela Colón", "description": "Disfruta de la iluminación y el ambiente bohemio.", "challenge": "Buscar la estatua o rincón más escondido de la plaza.", "tips": "Hay artistas y músicos en las noches de fin de semana.", "estimatedTime": "1 hora", "xpBase": 30, "costLevel": 1, "ubGeo": const GeoPoint(-17.3790, -66.1530)},
      {"number": 35, "type": "pareja", "title": "Tarde de helados artesanales en la Recoleta", "emoji": "🍨", "category": "Gastronomía", "locName": "Recoleta", "description": "Recorrido por las heladerías para probar sabores únicos.", "challenge": "Probar un sabor de helado que nunca hayan probado antes.", "tips": "Prueba el helado de achachairú o maracuyá.", "estimatedTime": "1 hora", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 36, "type": "pareja", "title": "Visita al Palacio Portales", "emoji": "🏰", "category": "Cultura", "locName": "Palacio Portales", "description": "Recorrido por la arquitectura más lujosa de Cochabamba.", "challenge": "Tomar una foto imitando las poses de las estatuas.", "tips": "Revisa los horarios de visita guiada.", "estimatedTime": "1.5 horas", "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3830, -66.1490)},
      {"number": 37, "type": "pareja", "title": "Paseo en la Ciclovía de la Av. Pando", "emoji": "🚴", "category": "Aventura", "locName": "Av. Pando / Centro", "description": "Alquila una bicicleta y recorre la ciclovía un domingo.", "challenge": "Hacer la ruta completa sin bajarse de la bici.", "tips": "Lleva agua y protector solar.", "estimatedTime": "2 horas", "xpBase": 70, "costLevel": 1, "ubGeo": const GeoPoint(-17.3754, -66.1523)},
      {"number": 38, "type": "pareja", "title": "Cena romántica con música en vivo", "emoji": "🎻", "category": "Especiales", "locName": "Zona Norte / Recoleta", "description": "Reserva una mesa con serenata o música en vivo.", "challenge": "Pedirle una canción a los músicos para tu pareja.", "tips": "Reserva con anticipación.", "estimatedTime": "2-3 horas", "xpBase": 90, "costLevel": 2, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 39, "type": "pareja", "title": "Comprar artesanías en La Cancha", "emoji": "🧶", "category": "Cultura", "locName": "Mercado La Cancha", "description": "Busquen un recuerdo artesanal único juntos.", "challenge": "Regatear el precio de algo y conseguir un descuento.", "tips": "Cuidado con los bolsillos, es zona muy transitada.", "estimatedTime": "2 horas", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3900, -66.1600)},
      {"number": 40, "type": "pareja", "title": "Ver la puesta de sol en Pairumani", "emoji": "🌅", "category": "Miradores", "locName": "Pairumani", "description": "Un corto viaje en auto para ver un atardecer de película.", "challenge": "Hacer una vez de silencio total durante 5 minutos.", "tips": "LLega 30 min antes del ocaso.", "estimatedTime": "1.5 horas", "xpBase": 80, "costLevel": 1, "ubGeo": const GeoPoint(-17.3000, -66.2500)},
      {"number": 41, "type": "pareja", "title": "Almuerzo con silpancho", "emoji": "🥩", "category": "Gastronomía", "locName": "La Casa del Gordo", "description": "Un reto culinario para compartir este plato contundente.", "challenge": "Terminarse el plato entero (es muy grande).", "tips": "Pide un solo plato para compartir.", "estimatedTime": "1 hora", "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(-17.3800, -66.1600)},
      {"number": 42, "type": "pareja", "title": "Paseo nocturno por la Recoleta iluminada", "emoji": "✨", "category": "Urbanos", "locName": "Recoleta", "description": "Camina bajo las luces de la zona más moderna.", "challenge": "Entrar a una tienda de antigüedades o arte.", "tips": "La zona es segura para caminar de noche.", "estimatedTime": "1 hora", "xpBase": 40, "costLevel": 1, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 43, "type": "pareja", "title": "Convento de Santa Teresa", "emoji": "⛪", "category": "Cultura", "locName": "Centro Histórico", "description": "Visita este museo convento del siglo XVIII.", "challenge": "Encontrar la representación de la 'Santísima Trinidad'.", "tips": "Se necesita respeto y silencio.", "estimatedTime": "1.5 horas", "xpBase": 60, "costLevel": 2, "ubGeo": const GeoPoint(-17.3730, -66.1570)},
      {"number": 44, "type": "pareja", "title": "Compartir un pique macho en el Prado", "emoji": "🌶️", "category": "Gastronomía", "locName": "El Prado", "description": "Nada une más que atacar juntos este plato gigante.", "challenge": "No tomar agua hasta terminar el primer bocado picante.", "tips": "¡El pique es para compartir!", "estimatedTime": "1 hora", "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(-17.3790, -66.1520)},
      {"number": 45, "type": "pareja", "title": "Karaoke romántico en sala privada", "emoji": "🎤", "category": "Música", "locName": "Zona Norte", "description": "Alquilen una sala y canten a todo pulmón sin pena.", "challenge": "Cantar un dueto de pie y bailando.", "tips": "Pidan snacks y bebidas.", "estimatedTime": "2 horas", "xpBase": 100, "costLevel": 2, "ubGeo": const GeoPoint(-17.3850, -66.1450)},
      {"number": 46, "type": "pareja", "title": "Picnic con cuñapé y api en la laguna", "emoji": "🧺", "category": "Gastronomía", "locName": "Laguna Alalay", "description": "Compre cuñapés calientitos y api, y siéntense en el pasto.", "challenge": "No derramar el api morado en la ropa.", "tips": "Lleva una manta o tela para sentarse.", "estimatedTime": "1.5 horas", "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.4128, -66.1360)},
      {"number": 47, "type": "pareja", "title": "Tour de cafés especiales en la Recoleta", "emoji": "☕", "category": "Gastronomía", "locName": "Recoleta", "description": "Visita 2 o 3 cafeterías de especialidad y comparen sabores.", "challenge": "Preguntarle al barista por el origen de los granos.", "tips": "Pide un V60 o Chemex.", "estimatedTime": "2 horas", "xpBase": 70, "costLevel": 2, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 48, "type": "pareja", "title": "Recorrido colonial por la Calle España", "emoji": "🏛️", "category": "Cultura", "locName": "Calle España", "description": "Camina por las casas coloniales mejor conservadas.", "challenge": "Adivinar qué casa es la más antigua.", "tips": "Hay murallas y portones increíbles para fotos.", "estimatedTime": "1 hora", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3740, -66.1560)},
      {"number": 49, "type": "pareja", "title": "Noche de trova en un bar bohemio", "emoji": "🎸", "category": "Música", "locName": "Centro / Recoleta", "description": "Disfruta de poetas y músicos en vivo.", "challenge": "Pedir un tema en la ronda de trova.", "tips": "Llega temprano para conseguir mesa.", "estimatedTime": "2 horas", "xpBase": 90, "costLevel": 2, "ubGeo": const GeoPoint(-17.3820, -66.1550)},
      {"number": 50, "type": "pareja", "title": "Probar anticuchos en la Plazuela Colón", "emoji": "🍢", "category": "Gastronomía", "locName": "Plazuela Colón", "description": "La experiencia callejera nocturna por excelencia.", "challenge": "Echarle todo el ají llajwa que soporten.", "tips": "Ve a los carritos con buena iluminación.", "estimatedTime": "45 min", "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3790, -66.1530)},
      {"number": 51, "type": "pareja", "title": "Caminata romántica por Pairumani y su cascada", "emoji": "🏞️", "category": "Aventura", "locName": "Pairumani", "description": "Caminata suave rodeada de naturaleza hasta la cascada.", "challenge": "Mojarse los pies en la cascada sí o sí.", "tips": "Zapatos cerrados obligatorios.", "estimatedTime": "3 horas", "xpBase": 120, "costLevel": 2, "ubGeo": const GeoPoint(-17.3000, -66.2500)},
      {"number": 52, "type": "pareja", "title": "Ir juntos al Teatro Achá", "emoji": "🎭", "category": "Cultura", "locName": "Teatro Achá", "description": "Vistan el teatro más antiguo de Bolivia y asistan a una obra.", "challenge": "Ir vestidos un poco formales por una noche.", "tips": "Compren entradas con anticipación.", "estimatedTime": "3 horas", "xpBase": 130, "costLevel": 2, "ubGeo": const GeoPoint(-17.3730, -66.1570)},
      {"number": 53, "type": "pareja", "title": "Paseo en tranvía turístico", "emoji": "🚋", "category": "Urbanos", "locName": "Centro / Prado", "description": "Suban al tranvía para conocer la ciudad sin caminar.", "challenge": "Tomar una selfie con el conductor.", "tips": "Pregunta los horarios de salida.", "estimatedTime": "1.5 horas", "xpBase": 70, "costLevel": 2, "ubGeo": const GeoPoint(-17.3750, -66.1560)},
      {"number": 54, "type": "pareja", "title": "Peña folklórica con serenata en vivo", "emoji": "💃", "category": "Música", "locName": "Zona Norte / Centro", "description": "Bailen cueca o morenada mientras cenan.", "challenge": "Levantarse y bailar una canción juntos.", "tips": "Suelen pedir propina para los músicos.", "estimatedTime": "3 horas", "xpBase": 130, "costLevel": 3, "ubGeo": const GeoPoint(-17.3820, -66.1500)},
      {"number": 55, "type": "pareja", "title": "Tarde de compras en la Recoleta", "emoji": "🛍️", "category": "Urbanos", "locName": "Recoleta", "description": "Recorran las boutiques y tiendas de diseño local.", "challenge": "Elegir la ropa que el otro se debe probar.", "tips": "Apoyen el diseño local.", "estimatedTime": "2 horas", "xpBase": 60, "costLevel": 2, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 56, "type": "pareja", "title": "Iglesia de San Sebastián iluminada", "emoji": "✝️", "category": "Cultura", "locName": "Iglesia San Sebastián", "description": "Visita la iglesia más antigua en la noche para apreciar su fachada.", "challenge": "Aprender algo nuevo sobre la historia.", "tips": "La plaza alrededor es tranquila.", "estimatedTime": "45 min", "xpBase": 40, "costLevel": 1, "ubGeo": const GeoPoint(-17.3920, -66.1570)},
      {"number": 57, "type": "pareja", "title": "Degustación de chicharrón tradicional", "emoji": "🍖", "category": "Gastronomía", "locName": "Mercado / Restaurante", "description": "Busquen el mejor chicharrón del valle.", "challenge": "Encontrar el chicharrón más crujiente.", "tips": "Sírvelo con llajwa fresca y plátano.", "estimatedTime": "1 hora", "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(-17.3810, -66.1550)},
      {"number": 58, "type": "pareja", "title": "Paseo por la Feria de Punata", "emoji": "🌾", "category": "Cultura", "locName": "Punata", "description": "Viajen a la provincia para conocer su feria.", "challenge": "Comprar una fruta o verdura que no conozcan.", "tips": "Es un viaje de 40 min en auto.", "estimatedTime": "Medio día", "xpBase": 140, "costLevel": 2, "ubGeo": const GeoPoint(-17.4700, -66.2500)},
      {"number": 59, "type": "pareja", "title": "Museo Arqueológico en pareja", "emoji": "🏺", "category": "Cultura", "locName": "Museo Arqueológico", "description": "Descubre los vestigios de las culturas del valle.", "challenge": "Encontrar la pieza más antigua del museo.", "tips": "Tienen piezas de la cultura Tiwanaku.", "estimatedTime": "1.5 horas", "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3740, -66.1550)},
      {"number": 60, "type": "pareja", "title": "Noche cultural con música en vivo en un café", "emoji": "🎶", "category": "Música", "locName": "Cafés Culturales", "description": "Terminar el día en un café con artistas locales.", "challenge": "Comprarle un trago al artista de la noche.", "tips": "Apaga el celular y solo escucha.", "estimatedTime": "2 horas", "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(-17.3860, -66.1480)},
      {"number": 61, "type": "pareja", "title": "Senderismo romántico en Apote", "emoji": "🥾", "category": "Aventura", "locName": "Apote", "description": "Caminata de dificultad media con miradores naturales.", "challenge": "Llegar al mirador más alto y gritar el nombre del otro.", "tips": "Lleva al menos 2 litros de agua por persona.", "estimatedTime": "4 horas", "xpBase": 160, "costLevel": 1, "ubGeo": const GeoPoint(-17.3300, -66.2000)},
      {"number": 62, "type": "pareja", "title": "Taller de cerámica en pareja", "emoji": "🏺", "category": "Arte", "locName": "Talleres locales", "description": "Aprendan juntos a moldear el barro.", "challenge": "Hacer una pieza que el otro pueda adivinar qué es.", "tips": "Lleven ropa que puedan ensuciar.", "estimatedTime": "2.5 horas", "xpBase": 130, "costLevel": 3, "ubGeo": const GeoPoint(-17.3830, -66.1500)},
      {"number": 63, "type": "pareja", "title": "Escapada romántica a Incachaca", "emoji": "🌊", "category": "Aventura", "locName": "Incachaca", "description": "Conozcan las cascadas y puentes colgantes.", "challenge": "Cruzar el puente colgante sin soltarse de las manos.", "tips": "Entrada con costo simbólico.", "estimatedTime": "Medio día", "xpBase": 170, "costLevel": 2, "ubGeo": const GeoPoint(-17.4500, -66.1900)},
      {"number": 64, "type": "pareja", "title": "Cena en un hotel boutique en Cala Cala", "emoji": "🏨", "category": "Especiales", "locName": "Cala Cala", "description": "Una velada de lujo en uno de los hoteles más románticos.", "challenge": "Ordenar el plato más recomendado del chef.", "tips": "Ideal para aniversarios.", "estimatedTime": "3 horas", "xpBase": 140, "costLevel": 3, "ubGeo": const GeoPoint(-17.3900, -66.1410)},
      {"number": 65, "type": "pareja", "title": "Paseo en moto por Tiquipaya", "emoji": "🏍️", "category": "Aventura", "locName": "Tiquipaya", "description": "Alquilen una moto y recorran los campos.", "challenge": "Encontrar el mirador de la Virgen en el cerro.", "tips": "Siempre usar casco.", "estimatedTime": "3 horas", "xpBase": 150, "costLevel": 2, "ubGeo": const GeoPoint(-17.3400, -66.2200)},
      {"number": 66, "type": "pareja", "title": "Sesión de fotos en Totora colonial", "emoji": "📸", "category": "Arte", "locName": "Totora", "description": "Recorran las calles empedradas y casas coloniales.", "challenge": "Hacer una sesión de fotos estilo revista.", "tips": "Totora es súper fotogénico.", "estimatedTime": "Medio día", "xpBase": 160, "costLevel": 2, "ubGeo": const GeoPoint(-17.5100, -65.9900)},
      {"number": 67, "type": "pareja", "title": "Noche de vinos y jazz en Cochabamba", "emoji": "🍷", "category": "Música", "locName": "Zona Norte", "description": "Busquen un bar especializado en vinos bolivianos con jazz.", "challenge": "Probar un vino de altura.", "tips": "Los vinos bolivianos están ganando premios.", "estimatedTime": "2 horas", "xpBase": 120, "costLevel": 3, "ubGeo": const GeoPoint(-17.3840, -66.1460)},
      {"number": 68, "type": "pareja", "title": "Preparar juntos silpancho casero", "emoji": "👨‍🍳", "category": "En Casa", "locName": "Hogar", "description": "Compre los ingredientes y cocinen juntos.", "challenge": "Que quede más crujiente que en el restaurante.", "tips": "El secreto es la carne bien finita.", "estimatedTime": "2 horas", "xpBase": 110, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 69, "type": "pareja", "title": "Maratón de películas bolivianas", "emoji": "🎬", "category": "En Casa", "locName": "Hogar", "description": "Preparen piqueos y vean películas hechas en Bolivia.", "challenge": "Ver una película de la que nunca hayan oído hablar.", "tips": "Busquen 'El Presidente del Diablo'.", "estimatedTime": "4 horas", "xpBase": 100, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 70, "type": "pareja", "title": "Cata de vinos bolivianos en casa", "emoji": "🧐", "category": "En Casa", "locName": "Hogar", "description": "Compren 3 tipos de vino y hagan su propia cata.", "challenge": "Adivinar cuál es el más caro.", "tips": "Sirvan en copas diferentes.", "estimatedTime": "2 horas", "xpBase": 90, "costLevel": 2, "ubGeo": const GeoPoint(0, 0)},
      {"number": 71, "type": "pareja", "title": "Paseo en kayak en la Angostura", "emoji": "🛶", "category": "Aventura", "locName": "Laguna La Angostura", "description": "Remar juntos con el paisaje de los cerros de fondo.", "challenge": "No voltear el kayak.", "tips": "Usen chaleco salvavidas.", "estimatedTime": "3 horas", "xpBase": 170, "costLevel": 2, "ubGeo": const GeoPoint(-17.4100, -66.2500)},
      {"number": 72, "type": "pareja", "title": "Tour a Tarata colonial", "emoji": "🏘️", "category": "Escapadas", "locName": "Tarata", "description": "Visiten el pueblo y caminen por sus calles de cal y canto.", "challenge": "Probar el chicha de maíz tradicional.", "tips": "Hay buses desde Cochabamba.", "estimatedTime": "Todo el día", "xpBase": 180, "costLevel": 2, "ubGeo": const GeoPoint(-17.6200, -66.0400)},
      {"number": 73, "type": "pareja", "title": "Tarde romántica en Villa Tunari", "emoji": "🌴", "category": "Escapadas", "locName": "Villa Tunari", "description": "Viajen al trópico a disfrutar del calor y ríos.", "challenge": "Bañarse en el río Chapare.", "tips": "Lleven traje de baño y repelente.", "estimatedTime": "Fin de semana", "xpBase": 190, "costLevel": 3, "ubGeo": const GeoPoint(-16.9700, -65.4300)},
      {"number": 74, "type": "pareja", "title": "Paseo en bote en la laguna Corani", "emoji": "⛵", "category": "Aventura", "locName": "Laguna Corani", "description": "Disfruten del paisaje boscoso remando.", "challenge": "Remar al compás sin chocar.", "tips": "Lleven abrigo.", "estimatedTime": "Medio día", "xpBase": 180, "costLevel": 2, "ubGeo": const GeoPoint(-17.2285, -65.8821)},
      {"number": 75, "type": "pareja", "title": "Tarde de camping en el Parque Tunari", "emoji": "⛺", "category": "Aventura", "locName": "Parque Tunari", "description": "Acampen bajo las estrellas.", "challenge": "Cocinar algo en la fogata.", "tips": "Revisen permisos para acampar.", "estimatedTime": "24 horas", "xpBase": 200, "costLevel": 2, "ubGeo": const GeoPoint(-17.3500, -66.1200)},
      {"number": 76, "type": "pareja", "title": "Cena con velas en casa", "emoji": "🕯️", "category": "Especiales", "locName": "Hogar", "description": "Preparen un ambiente romántico y cocinen algo típico.", "challenge": "Cenar sin celulares.", "tips": "La iluminación lo es todo.", "estimatedTime": "2.5 horas", "xpBase": 120, "costLevel": 2, "ubGeo": const GeoPoint(0, 0)},
      {"number": 77, "type": "pareja", "title": "Escribir juntos su lista de sueños", "emoji": "📝", "category": "Especiales", "locName": "Un café tranquilo", "description": "Escriban 10 cosas que quieren hacer juntos.", "challenge": "Incluir al menos un viaje loco en la lista.", "tips": "No juzguen las ideas del otro.", "estimatedTime": "2 horas", "xpBase": 140, "costLevel": 1, "ubGeo": const GeoPoint(-17.3850, -66.1480)},
      {"number": 78, "type": "pareja", "title": "Escapada de fin de semana a Aiquile", "emoji": "🎶", "category": "Escapadas", "locName": "Aiquile", "description": "Visiten la capital del charango.", "challenge": "Comprar un charango pequeño.", "tips": "Festival de charango en noviembre.", "estimatedTime": "Fin de semana", "xpBase": 190, "costLevel": 3, "ubGeo": const GeoPoint(-18.1800, -65.3700)},
      {"number": 79, "type": "pareja", "title": "Fogata en un camping con guitarra", "emoji": "🔥", "category": "Aventura", "locName": "Zona Tunari / Liriuni", "description": "La clásica fogata cantando y comiendo marshmallows.", "challenge": "Inventar una historia de terror.", "tips": "Llevar guitarra si alguien sabe tocar.", "estimatedTime": "4 horas", "xpBase": 160, "costLevel": 2, "ubGeo": const GeoPoint(-17.3100, -66.1500)},
      {"number": 80, "type": "pareja", "title": "Cena bajo las estrellas en la Angostura", "emoji": "🌌", "category": "Especiales", "locName": "Laguna La Angostura", "description": "Preparen una canasta y vayan a cenar de noche.", "challenge": "Encontrar una constelación.", "tips": "Lleven manta y linterna.", "estimatedTime": "3 horas", "xpBase": 250, "costLevel": 3, "ubGeo": const GeoPoint(-17.4100, -66.2500)}
    ];

    final List<Map<String, dynamic>> groupAdventures = [
      {"number": 81, "type": "grupo", "title": "Asado en el Parque Tunari", "emoji": "🥩", "category": "Gastronomía", "locName": "Parque Tunari", "description": "Reúnanse para hacer un asado en los hornos del parque.", "challenge": "Que cada uno traiga un ingrediente secreto.", "tips": "Lleguen temprano para conseguir un buen sitio.", "estimatedTime": "4 horas", "xpBase": 100, "costLevel": 2, "ubGeo": const GeoPoint(-17.3500, -66.1200)},
      {"number": 82, "type": "grupo", "title": "Noche de karaoku en sala privada", "emoji": "🎤", "category": "Música", "locName": "Zona Norte", "description": "Alquilen una sala grande y canten hasta quedarse sin voz.", "challenge": "Hacer un dueto desafiante.", "tips": "Pidan picadas para compartir.", "estimatedTime": "3 horas", "xpBase": 120, "costLevel": 2, "ubGeo": const GeoPoint(-17.3850, -66.1450)},
      {"number": 83, "type": "grupo", "title": "Jugar al fútbol en la Cancha del barrio", "emoji": "⚽", "category": "Aventura", "locName": "Cancha Local", "description": "Armen un partido amigos contra amigos.", "challenge": "Hacer al menos un gol.", "tips": "Lleven agua y protegetores.", "estimatedTime": "2 horas", "xpBase": 80, "costLevel": 1, "ubGeo": const GeoPoint(-17.3810, -66.1550)},
      {"number": 84, "type": "grupo", "title": "Escape Room de Terror", "emoji": "🔐", "category": "Aventura", "locName": "Centro", "description": "Resuelvan acertijos para escapar de la habitación a oscuras.", "challenge": "Escapar en menos de 45 minutos.", "tips": "La comunicación es la clave.", "estimatedTime": "1.5 horas", "xpBase": 150, "costLevel": 3, "ubGeo": const GeoPoint(-17.3750, -66.1560)},
      {"number": 85, "type": "grupo", "title": "Ir al Estadio Félix Capriles", "emoji": "🏟️", "category": "Aventura", "locName": "Estadio Félix Capriles", "description": "Alienten a Auroro o a Litoral todos juntos.", "challenge": "Comprar algo de un vendedor ambulante.", "tips": "Cuidado con la euforia de la hinchada.", "estimatedTime": "3 horas", "xpBase": 90, "costLevel": 1, "ubGeo": const GeoPoint(-17.3820, -66.1480)},
      {"number": 86, "type": "grupo", "title": "Tarde de Bowling", "emoji": "🎳", "category": "Urbanos", "locName": "Zona Norte", "description": "Compitan a ver quién tira más pinos.", "challenge": "Hacer un Strike.", "tips": "Pidan pizza mientras juegan.", "estimatedTime": "2 horas", "xpBase": 100, "costLevel": 2, "ubGeo": const GeoPoint(-17.3840, -66.1460)},
      {"number": 87, "type": "grupo", "title": "Noche de juegos de mesa", "emoji": "🎲", "category": "En Casa", "locName": "Hogar de alguien", "description": "Jueguen Catan, UNO o Party&Co.", "challenge": "Que el perdedor pida la pizza.", "tips": "Prohibido mirar celulares.", "estimatedTime": "3 horas", "xpBase": 80, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 88, "type": "grupo", "title": "Caminata grupal en Pairumani", "emoji": "🥾", "category": "Aventura", "locName": "Pairumani", "description": "Vayan en manada a la cascada.", "challenge": "Tomar una foto grupal saltando.", "tips": "Zapatos antiderrapantes.", "estimatedTime": "3 horas", "xpBase": 120, "costLevel": 1, "ubGeo": const GeoPoint(-17.3000, -66.2500)},
      {"number": 89, "type": "grupo", "title": "Comer Pique Macho Gigante", "emoji": "🌶️", "category": "Gastronomía", "locName": "El Prado", "description": "Pidan el pique más grande del menú y atáquenlo entre todos.", "challenge": "Terminarlo sin dejar nada.", "tips": "Pidan extra llajwa.", "estimatedTime": "1.5 horas", "xpBase": 100, "costLevel": 2, "ubGeo": const GeoPoint(-17.3790, -66.1520)},
      {"number": 90, "type": "grupo", "title": "Tarde de Paintball", "emoji": "🎯", "category": "Aventura", "locName": "Exteriores Cbba", "description": "Dividan equipos y a disparar.", "challenge": "No ser el primero eliminado.", "tips": "Usen ropa que puedan manchar.", "estimatedTime": "3 horas", "xpBase": 150, "costLevel": 3, "ubGeo": const GeoPoint(-17.3830, -66.1500)},
      {"number": 91, "type": "grupo", "title": "Tour de Chicharrón", "emoji": "🍖", "category": "Gastronomía", "locName": "Varios", "description": "Vayan a 2-3 lugares probando quién tiene el mejor chicharrón.", "challenge": "Votar por el mejor lugar.", "tips": "Vayan con hambre.", "estimatedTime": "3 horas", "xpBase": 130, "costLevel": 2, "ubGeo": const GeoPoint(-17.3810, -66.1550)},
      {"number": 92, "type": "grupo", "title": "Paseo en Bote en la Angostura", "emoji": "⛵", "category": "Aventura", "locName": "Laguna La Angostura", "description": "Alquilen un bote de remos y recorran la laguna.", "challenge": "Remar todos al mismo tiempo sin chocar.", "tips": "Chaleco salvavidas siempre.", "estimatedTime": "2 horas", "xpBase": 110, "costLevel": 2, "ubGeo": const GeoPoint(-17.4100, -66.2500)},
      {"number": 93, "type": "grupo", "title": "Clase de Cocina Grupal", "emoji": "👨‍🍳", "category": "Gastronomía", "locName": "Taller Local", "description": "Aprendan a cocinar algo típico juntos.", "challenge": "Dividir tareas sin pelear.", "tips": "Lleven delantal.", "estimatedTime": "3 horas", "xpBase": 140, "costLevel": 3, "ubGeo": const GeoPoint(-17.3830, -66.1500)},
      {"number": 94, "type": "grupo", "title": "Fútbol Playa en la Angostura", "emoji": "🏖️", "category": "Aventura", "locName": "Laguna La Angostura", "description": "Armen una cancha en la orilla y jueguen descalzos.", "challenge": "Hacer un gol de chilena.", "tips": "Lleven protector solar.", "estimatedTime": "3 horas", "xpBase": 100, "costLevel": 1, "ubGeo": const GeoPoint(-17.4100, -66.2500)},
      {"number": 95, "type": "grupo", "title": "Noche de Peña Folklorica", "emoji": "💃", "category": "Música", "locName": "Centro", "description": "Bailen toda la noche en una peña tradicional.", "challenge": "Bailar una morenada grupal.", "tips": "Reserven mesa.", "estimatedTime": "4 horas", "xpBase": 160, "costLevel": 3, "ubGeo": const GeoPoint(-17.3820, -66.1500)},
      {"number": 96, "type": "grupo", "title": "Maratón de Películas de Terror", "emoji": "👻", "category": "En Casa", "locName": "Hogar", "description": "Cierren las luces y vean 3 películas de terror.", "challenge": "No taparse los ojos.", "tips": "Preparar palomitas y cobijas.", "estimatedTime": "6 horas", "xpBase": 120, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 97, "type": "grupo", "title": "Picnic en la Laguna Alalay", "emoji": "🧺", "category": "Naturaleza", "locName": "Laguna Alalay", "description": "Cada quien lleva algo de comer y comparten.", "challenge": "Probar la comida de todos.", "tips": "Lleven una manta grande.", "estimatedTime": "2 horas", "xpBase": 70, "costLevel": 1, "ubGeo": const GeoPoint(-17.4128, -66.1360)},
      {"number": 98, "type": "grupo", "title": "Ir al Cine en Grupo", "emoji": "🎬", "category": "Urbanos", "locName": "Cine Center", "description": "Vayan todos a ver el estreno juntos.", "challenge": "Sentarse todos juntos en la fila del medio.", "tips": "Compren entradas online antes.", "estimatedTime": "3 horas", "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(-17.3830, -66.1490)},
      {"number": 99, "type": "grupo", "title": "Ir a comer Salteñas", "emoji": "🥟", "category": "Gastronomía", "locName": "Av. Pando", "description": "Quédense sin salteñas o pidan 2 rondas.", "challenge": "El último en terminar paga la cuenta.", "tips": "Llegar antes de las 10 AM.", "estimatedTime": "1 hora", "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3754, -66.1523)},
      {"number": 100, "type": "grupo", "title": "Paseo en Bici por el Prado", "emoji": "🚴", "category": "Urbanos", "locName": "El Prado", "description": "Alquilen bicis y recorran el centro un domingo.", "challenge": "Hacer una carrera hasta la Plaza Principal.", "tips": "Cuidado con los peatones.", "estimatedTime": "2 horas", "xpBase": 80, "costLevel": 1, "ubGeo": const GeoPoint(-17.3790, -66.1520)},
      {"number": 101, "type": "grupo", "title": "Tarde de Fotos Grupales", "emoji": "📸", "category": "Arte", "locName": "Recoleta", "description": "Tomen fotos creativas y graciosas por la zona.", "challenge": "Recrear una escena de película.", "tips": "La luz dorada de la tarde es ideal.", "estimatedTime": "2 horas", "xpBase": 70, "costLevel": 1, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 102, "type": "grupo", "title": "Visitar Palacio Portales", "emoji": "🏰", "category": "Cultura", "locName": "Palacio Portales", "description": "Recorran los jardines y el interior.", "challenge": "Tomar la foto más dramática posible.", "tips": "Guía incluida a veces.", "estimatedTime": "1.5 horas", "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3830, -66.1490)},
      {"number": 103, "type": "grupo", "title": "Cocinar una Paya de Pollo", "emoji": "🍲", "category": "En Casa", "locName": "Hogar", "description": "Armen una olla gigante entre todos.", "challenge": "Pelar 1 kg de papas sin quejarse.", "tips": "Compartan los gastos.", "estimatedTime": "3 horas", "xpBase": 100, "costLevel": 2, "ubGeo": const GeoPoint(0, 0)},
      {"number": 104, "type": "grupo", "title": "Paseo Nocturno Centro Histórico", "emoji": "🌙", "category": "Urbanos", "locName": "Centro", "description": "Recorran las plazuelas iluminadas contando historias de miedo.", "challenge": "Sustos permitidos.", "tips": "No asustar a los transeúntes.", "estimatedTime": "2 horas", "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3730, -66.1570)},
      {"number": 105, "type": "grupo", "title": "Jugar al Cacho (Dados)", "emoji": "🎲", "category": "En Casa", "locName": "Hogar", "description": "El juego boliviano por excelencia con amigos.", "challenge": "Sacar un Cacho Grande.", "tips": "Jueguen con postres como apuesta.", "estimatedTime": "2 horas", "xpBase": 80, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 106, "type": "grupo", "title": "Ir a un Concierto Local", "emoji": "🎸", "category": "Música", "locName": "Teatro Achá / Bares", "description": "Apoyen a bandas locales en vivo.", "challenge": "Comprar un sticker del grupo.", "tips": "Siempre hay buena onda.", "estimatedTime": "3 horas", "xpBase": 110, "costLevel": 2, "ubGeo": const GeoPoint(-17.3730, -66.1570)},
      {"number": 107, "type": "grupo", "title": "Ruta de Anticuchos", "emoji": "🍢", "category": "Gastronomía", "locName": "Colón / Quillacollo", "description": "Recorran los carritos nocturnos.", "challenge": "Probar los de 3 lugares distintos.", "tips": "Los de la Plazuela son clásico.", "estimatedTime": "2 horas", "xpBase": 80, "costLevel": 1, "ubGeo": const GeoPoint(-17.3790, -66.1530)},
      {"number": 108, "type": "grupo", "title": "Tarde de Voluntariado", "emoji": "🤝", "category": "Especiales", "locName": "Albergue / Refugio", "description": "Hagan algo bueno por la comunidad juntos.", "challenge": "No quejarse del trabajo.", "tips": "Llevar ropa vieja o comida.", "estimatedTime": "4 horas", "xpBase": 150, "costLevel": 0, "ubGeo": const GeoPoint(-17.3830, -66.1500)},
      {"number": 109, "type": "grupo", "title": "Hacer una Fogata en Liriuni", "emoji": "🔥", "category": "Aventura", "locName": "Liriuni", "description": "Suban, hagan fuego y cuenten anécdotas.", "challenge": "Prender el fuego con 1 fósforo.", "tips": "Leña seca y abrigo.", "estimatedTime": "5 horas", "xpBase": 130, "costLevel": 2, "ubGeo": const GeoPoint(-17.3100, -66.1500)},
      {"number": 110, "type": "grupo", "title": "Fiesta Sorpresa para un Amigo", "emoji": "🎉", "category": "Especiales", "locName": "Hogar", "description": "Organícenle una fiesta inolvidable a alguien del grupo.", "challenge": "Que no se entere hasta el último segundo.", "tips": "Coordinen en grupo de WhatsApp en silencio.", "estimatedTime": "5 horas", "xpBase": 180, "costLevel": 3, "ubGeo": const GeoPoint(0, 0)},
    ];

    final WriteBatch batch = firestore.batch();
    final CollectionReference adventuresRef = firestore.collection('adventures');

    for (var aventura in [...soloAdventures, ...coupleAdventures, ...groupAdventures]) {
      DocumentReference docRef = adventuresRef.doc(aventura['number'].toString());
      batch.set(docRef, aventura);
    }

    try {
      await batch.commit();
      debugPrint('✅ 110 Aventuras (30 Solo, 50 Pareja, 30 Grupo) insertadas!');
    } catch (e) {
      debugPrint('🔥 Error insertando aventuras: $e');
      rethrow;
    }
  }
}