import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

class FirebaseSeeder {
  static Future<void> seedDatabase() async {
    final FirebaseFirestore firestore = FirebaseFirestore.instance;
    
    debugPrint('Iniciando inserción de 50 aventuras...');

    // 50 Aventuras basadas en los PDFs de Cochabamba
    final List<Map<String, dynamic>> aventurasIniciales = [
      {"number": 1, "title": "Subida al Cristo de la Concordia al atardecer", "emoji": "✝️", "category": "Miradores", "locName": "Cristo de la Concordia", "description": "Sube los escalones o toma el teleférico para ver caer el sol sobre la ciudad de la eterna primavera.", "challenge": "Tomarse una foto abrazando la ciudad al fondo.", "tips": "Lleva una chompa, a esa hora refresca.", "estimatedTime": "1-2 horas", "valid_modes": ["solo", "pareja", "grupo"], "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.38414, -66.13553)},
      {"number": 2, "title": "Paseo romántico en la Laguna Alalay", "emoji": "🦆", "category": "Naturaleza", "locName": "Laguna Alalay", "description": "Una caminata tranquila rodeando la laguna, ideal para conversar y disfrutar de la brisa.", "challenge": "Comprar algo de comer a los patos y peces del lago.", "tips": "Evita las horas de sol más fuerte (12:00 - 15:00).", "estimatedTime": "1 hora", "valid_modes": ["pareja", "grupo"], "xpBase": 40, "costLevel": 1, "ubGeo": const GeoPoint(-17.4128, -66.1360)},
      {"number": 3, "title": "Desayuno con salteñas en la Av. Pando", "emoji": "🥟", "category": "Gastronomía", "locName": "Avenida Pando", "description": "Empieza el día con el sabor más tradicional de la ciudad en una de las avenidas más icónicas.", "challenge": "Comer la salteña sin que se caiga una gota de jugo.", "tips": "Las salteñas se acaban temprano, ve antes de las 10:00 AM.", "estimatedTime": "45 min", "valid_modes": ["solo", "pareja", "grupo"], "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3754, -66.1523)},
      {"number": 4, "title": "Caminata por la Plaza Colón de noche", "emoji": "🌙", "category": "Urbanos", "locName": "Plazuela Colón", "description": "Disfruta de la iluminación y el ambiente bohemio de esta tradicional plazuela cochabambina.", "challenge": "Buscar la estatua o rincón más escondido de la plaza.", "tips": "Hay artistas y músicos en las noches de fin de semana.", "estimatedTime": "1 hora", "valid_modes": ["pareja", "solo"], "xpBase": 30, "costLevel": 1, "ubGeo": const GeoPoint(-17.3790, -66.1530)},
      {"number": 5, "title": "Tarde de helados artesanales en la Recoleta", "emoji": "🍨", "category": "Gastronomía", "locName": "Recoleta", "description": "Recorrido por las heladerías de la zona para probar sabores únicos del Valle.", "challenge": "Probar un sabor de helado que nunca hayan probado antes.", "tips": "Prueba el helado de achachairú o maracuyá.", "estimatedTime": "1 hora", "valid_modes": ["pareja", "grupo"], "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 6, "title": "Visita al Palacio Portales", "emoji": "🏰", "category": "Cultura", "locName": "Palacio Portales", "description": "Recorrido por la arquitectura más lujosa y europea de Cochabamba, un viaje al pasado.", "challenge": "Tomar una foto imitando las poses de las estatuas del jardín.", "tips": "Revisa los horarios de visita guiada.", "estimatedTime": "1.5 horas", "valid_modes": ["pareja", "solo", "grupo"], "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3830, -66.1490)},
      {"number": 7, "title": "Paseo en la Ciclovía de la Av. Pando", "emoji": "🚴", "category": "Aventura", "locName": "Av. Pando / Centro", "description": "Alquila una bicicleta y recorre la ciclovía un domingo por la mañana con los locales.", "challenge": "Hacer la ruta completa sin bajarse de la bici.", "tips": "Lleva agua y protector solar.", "estimatedTime": "2 horas", "valid_modes": ["solo", "pareja", "grupo"], "xpBase": 70, "costLevel": 1, "ubGeo": const GeoPoint(-17.3754, -66.1523)},
      {"number": 8, "title": "Cena romántica con música en vivo", "emoji": "🎻", "category": "Especiales", "locName": "Zona Norte / Recoleta", "description": "Reserva una mesa en un restaurante con serenata o música en vivo para una velada especial.", "challenge": "Pedirle una canción a los músicos para tu pareja.", "tips": "Reserva con anticipación, los buenos lugares se llenan.", "estimatedTime": "2-3 horas", "valid_modes": ["pareja"], "xpBase": 90, "costLevel": 2, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 9, "title": "Comprar artesanías en La Cancha", "emoji": "🧶", "category": "Cultura", "locName": "Mercado La Cancha", "description": "Adéntrate en el mercado más grande de Bolivia y busca un recuerdo artesanal único.", "challenge": "Regatear el precio de algo y conseguir un descuento.", "tips": "Cuidado con los bolsillos, es zona muy transitada.", "estimatedTime": "2 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3900, -66.1600)},
      {"number": 10, "title": "Ver la puesta de sol en Pairumani", "emoji": "🌅", "category": "Miradores", "locName": "Pairumani", "description": "Un corto viaje en auto hasta el puente de Pairumani para ver un atardecer de película sobre el río.", "challenge": "Hacer una vez de silencio total durante 5 minutos escuchando el río.", "tips": "LLega 30 min antes del ocaso.", "estimatedTime": "1.5 horas", "valid_modes": ["pareja", "solo"], "xpBase": 80, "costLevel": 1, "ubGeo": const GeoPoint(-17.3000, -66.2500)},
      {"number": 11, "title": "Almuerzo con silpancho en La Casa del Gordo", "emoji": "🥩", "category": "Gastronomía", "locName": "La Casa del Gordo", "description": "Un reto culinario para compartir uno de los platos más contundentes y deliciosos del valle.", "challenge": "Terminarse el plato entero (es muy grande).", "tips": "Pide un solo plato para compartir si no comen mucho.", "estimatedTime": "1 hora", "valid_modes": ["pareja", "grupo"], "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(-17.3800, -66.1600)},
      {"number": 12, "title": "Paseo nocturno por la Recoleta iluminada", "emoji": "✨", "category": "Urbanos", "locName": "Recoleta", "description": "Camina bajo las luces de la zona más moderna y bohemia de la ciudad.", "challenge": "Entrar a una tienda de antigüedades o arte que nunca hayan notado.", "tips": "La zona es segura para caminar de noche.", "estimatedTime": "1 hora", "valid_modes": ["pareja", "solo"], "xpBase": 40, "costLevel": 1, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 13, "title": "Convento de Santa Teresa", "emoji": "⛪", "category": "Cultura", "locName": "Centro Histórico", "description": "Visita este museo convento del siglo XVIII, lleno de historia y arte colonial.", "challenge": "Encontrar la representación de la 'Santísima Trinidad' en el museo.", "tips": "Se necesita respeto y silencio dentro del convento.", "estimatedTime": "1.5 horas", "valid_modes": ["pareja", "solo", "grupo"], "xpBase": 60, "costLevel": 2, "ubGeo": const GeoPoint(-17.3730, -66.1570)},
      {"number": 14, "title": "Compartir un pique macho en el Prado", "emoji": "🌶️", "category": "Gastronomía", "locName": "El Prado", "description": "Nada une más a una pareja que atacar juntos este plato gigante de carne, papas y huevo.", "challenge": "No tomar agua hasta terminar el primer bocado picante.", "tips": "El pique es para compartir, ¡no te choques solo!", "estimatedTime": "1 hora", "valid_modes": ["pareja", "grupo"], "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(-17.3790, -66.1520)},
      {"number": 15, "title": "Karaoke romántico en sala privada", "emoji": "🎤", "category": "Música", "locName": "Zona Norte", "description": "Alquilen una sala de karaoke y canten a todo pulmón sus canciones favoritas sin pena.", "challenge": "Cantar un dueto de pie y bailando.", "tips": "Pidan snacks y bebidas para hacer la sesión más amena.", "estimatedTime": "2 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 100, "costLevel": 2, "ubGeo": const GeoPoint(-17.3850, -66.1450)},
      {"number": 16, "title": "Picnic con cuñapé y api en la laguna", "emoji": "🧺", "category": "Gastronomía", "locName": "Laguna Alalay", "description": "Compre cuñapés calientitos y api, y siéntense en el pasto a disfrutar del atardecer.", "challenge": "No derramar el api morado en la ropa.", "tips": "Lleva una manta o tela para sentarse.", "estimatedTime": "1.5 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.4128, -66.1360)},
      {"number": 17, "title": "Tour de cafés especiales en la Recoleta", "emoji": "☕", "category": "Gastronomía", "locName": "Recoleta", "description": "Visita 2 o 3 cafeterías de especialidad y comparen métodos de extracción y sabores.", "challenge": "Preguntarle al barista por el origen de los granos.", "tips": "Pide un V60 o un Chemex para probar el café de verdad.", "estimatedTime": "2 horas", "valid_modes": ["pareja"], "xpBase": 70, "costLevel": 2, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 18, "title": "Recorrido colonial por la Calle España", "emoji": "🏛️", "category": "Cultura", "locName": "Calle España", "description": "Camina por las casas coloniales mejor conservadas de la ciudad.", "challenge": "Adivinar qué casa es la más antigua de la calle.", "tips": "Hay murallas y portones increíbles para fotos.", "estimatedTime": "1 hora", "valid_modes": ["pareja", "solo"], "xpBase": 50, "costLevel": 1, "ubGeo": const GeoPoint(-17.3740, -66.1560)},
      {"number": 19, "title": "Noche de trova en un bar bohemio", "emoji": "🎸", "category": "Música", "locName": "Centro / Recoleta", "description": "Disfruta de poetas y músicos en vivo en un ambiente íntimo y cultural.", "challenge": "Pedir un tema en la ronda de trova.", "tips": "Llega temprano para conseguir mesa cerca del escenario.", "estimatedTime": "2 horas", "valid_modes": ["pareja"], "xpBase": 90, "costLevel": 2, "ubGeo": const GeoPoint(-17.3820, -66.1550)},
      {"number": 20, "title": "Probar anticuchos en la Plazuela Colón", "emoji": "🍢", "category": "Gastronomía", "locName": "Plazuela Colón", "description": "La experiencia callejera nocturna por excelencia de Cochabamba.", "challenge": "Echarle todo el ají llajwa que soporten.", "tips": "Solo ve a los carritos con buena iluminación y movimiento.", "estimatedTime": "45 min", "valid_modes": ["pareja", "grupo"], "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3790, -66.1530)},
      {"number": 21, "title": "Caminata romántica por Pairumani y su cascada", "emoji": "🏞️", "category": "Aventura", "locName": "Pairumani", "description": "Caminata suave rodeada de naturaleza hasta la pequeña cascada.", "challenge": "Mojarse los pies en la cascada sí o sí.", "tips": "Zapatos cerrados y antiderrapantes obligatorios.", "estimatedTime": "3 horas", "valid_modes": ["pareja", "solo"], "xpBase": 120, "costLevel": 2, "ubGeo": const GeoPoint(-17.3000, -66.2500)},
      {"number": 22, "title": "Ir juntos al Teatro Achá", "emoji": "🎭", "category": "Cultura", "locName": "Teatro Achá", "description": "Vistan el teatro más antiguo de Bolivia y asistan a una obra o concierto.", "challenge": "Ir vestidos un poco formales por una noche.", "tips": "Compren entradas con anticipación en taquilla.", "estimatedTime": "3 horas", "valid_modes": ["pareja"], "xpBase": 130, "costLevel": 2, "ubGeo": const GeoPoint(-17.3730, -66.1570)},
      {"number": 23, "title": "Paseo en tranvía turístico", "emoji": "🚋", "category": "Urbanos", "locName": "Centro / Prado", "description": "Suban al tranvía para conocer la historia de la ciudad sin caminar.", "challenge": "Tomar una selfie con el conductor.", "tips": "Pregunta los horarios de salida en la Plaza Principal.", "estimatedTime": "1.5 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 70, "costLevel": 2, "ubGeo": const GeoPoint(-17.3750, -66.1560)},
      {"number": 24, "title": "Peña folklórica con serenata en vivo", "emoji": "💃", "category": "Música", "locName": "Zona Norte / Centro", "description": "Bailen cueca o morenada mientras cenan en una peña tradicional cochabambina.", "challenge": "Levantarse y bailar una canción juntos.", "tips": "Suelen pedir propina para los músicos.", "estimatedTime": "3 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 130, "costLevel": 3, "ubGeo": const GeoPoint(-17.3820, -66.1500)},
      {"number": 25, "title": "Tarde de compras en la Recoleta", "emoji": "🛍️", "category": "Urbanos", "locName": "Recoleta", "description": "Recorran las boutiques y tiendas de diseño local.", "challenge": "Elegir la ropa que el otro se debe probar.", "tips": "Apoyen el diseño local cochabambino.", "estimatedTime": "2 horas", "valid_modes": ["pareja"], "xpBase": 60, "costLevel": 2, "ubGeo": const GeoPoint(-17.3870, -66.1470)},
      {"number": 26, "title": "Iglesia de San Sebastián iluminada", "emoji": "✝️", "category": "Cultura", "locName": "Iglesia San Sebastián", "description": "Visita la iglesia más antigua de la ciudad en la noche para apreciar su fachada iluminada.", "challenge": "Aprender algo nuevo sobre la historia de la iglesia.", "tips": "La plaza alrededor es un lugar tranquilo.", "estimatedTime": "45 min", "valid_modes": ["pareja", "solo"], "xpBase": 40, "costLevel": 1, "ubGeo": const GeoPoint(-17.3920, -66.1570)},
      {"number": 27, "title": "Degustación de chicharrón tradicional", "emoji": "🍖", "category": "Gastronomía", "locName": "Mercado / Restaurante", "description": "Busquen el mejor chicharrón del valle para darse un gusto bien cochabambino.", "challenge": "Encontrar el chicharrón más crujiente de la ciudad.", "tips": "Sírvelo con llajwa fresca y plátano.", "estimatedTime": "1 hora", "valid_modes": ["pareja", "grupo"], "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(-17.3810, -66.1550)},
      {"number": 28, "title": "Paseo por la Feria de Punata", "emoji": "🌾", "category": "Cultura", "locName": "Punata", "description": "Viajen a la provincia para conocer su feria llena de productos agrícolas y comida típica.", "challenge": "Comprar una fruta o verdura que no conozcan y probarla.", "tips": "Es un viaje de unos 40 min en auto desde Cbba.", "estimatedTime": "Medio día", "valid_modes": ["pareja", "grupo"], "xpBase": 140, "costLevel": 2, "ubGeo": const GeoPoint(-17.4700, -66.2500)},
      {"number": 29, "title": "Museo Arqueológico en pareja", "emoji": "🏺", "category": "Cultura", "locName": "Museo Arqueológico", "description": "Descubre los vestigios de las culturas que habitaron el valle antes de la colonia.", "challenge": "Encontrar la pieza más antigua del museo.", "tips": "Tienen piezas increíbles de la cultura Tiwanaku.", "estimatedTime": "1.5 horas", "valid_modes": ["pareja", "solo"], "xpBase": 60, "costLevel": 1, "ubGeo": const GeoPoint(-17.3740, -66.1550)},
      {"number": 30, "title": "Noche cultural con música en vivo en un café", "emoji": "🎶", "category": "Música", "locName": "Cafés Culturales", "description": "Terminar el día en un café con ambiente relajado y artistas locales tocando acústico.", "challenge": "Comprarle un trago al artista de la noche.", "tips": "Apaga el celular y solo escucha.", "estimatedTime": "2 horas", "valid_modes": ["pareja"], "xpBase": 80, "costLevel": 2, "ubGeo": const GeoPoint(-17.3860, -66.1480)},
      {"number": 31, "title": "Senderismo romántico en Apote", "emoji": "🥾", "category": "Aventura", "locName": "Apote", "description": "Una caminata de dificultad media con miradores naturales de todo el valle.", "challenge": "Llegar al mirador más alto y gritar el nombre del otro.", "tips": "Lleva al menos 2 litros de agua por persona.", "estimatedTime": "4 horas", "valid_modes": ["pareja", "solo"], "xpBase": 160, "costLevel": 1, "ubGeo": const GeoPoint(-17.3300, -66.2000)},
      {"number": 32, "title": "Taller de cerámica en pareja", "emoji": "🏺", "category": "Arte", "locName": "Talleres locales", "description": "Aprendan juntos a moldear el barro y creen su propia pieza de recuerdo.", "challenge": "Hacer una pieza que el otro pueda adivinar qué es.", "tips": "Lleven ropa que puedan ensuciar.", "estimatedTime": "2.5 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 130, "costLevel": 3, "ubGeo": const GeoPoint(-17.3830, -66.1500)},
      {"number": 33, "title": "Escapada romántica a Incachaca", "emoji": "🌊", "category": "Aventura", "locName": "Incachaca", "description": "Conozcan las cascadas y puentes colgantes de este mágico lugar ecológico.", "challenge": "Cruzar el puente colgante sin soltarse de las manos.", "tips": "Entrada con costo simbólico. Llevar repelente.", "estimatedTime": "Medio día", "valid_modes": ["pareja"], "xpBase": 170, "costLevel": 2, "ubGeo": const GeoPoint(-17.4500, -66.1900)},
      {"number": 34, "title": "Cena en un hotel boutique en Cala Cala", "emoji": "🏨", "category": "Especiales", "locName": "Cala Cala", "description": "Una velada de lujo en uno de los hoteles más románticos de la zona.", "challenge": "Ordenar el plato más recomendado del chef.", "tips": "Ideal para celebrar aniversarios o fechas especiales.", "estimatedTime": "3 horas", "valid_modes": ["pareja"], "xpBase": 140, "costLevel": 3, "ubGeo": const GeoPoint(-17.3900, -66.1410)},
      {"number": 35, "title": "Paseo en moto por Tiquipaya", "emoji": "🏍️", "category": "Aventura", "locName": "Tiquipaya", "description": "Alquilen una moto y recorran las calles y campos de Tiquipaya con el viento en la cara.", "challenge": "Encontrar el mirador de la Virgen en el cerro.", "tips": "Siempre usar casco y manejar con precaución.", "estimatedTime": "3 horas", "valid_modes": ["pareja"], "xpBase": 150, "costLevel": 2, "ubGeo": const GeoPoint(-17.3400, -66.2200)},
      {"number": 36, "title": "Sesión de fotos en Totora colonial", "emoji": "📸", "category": "Arte", "locName": "Totora", "description": "Recorran las calles empedradas y casas coloniales de este pueblo mágico con la cámara en mano.", "challenge": "Hacer una sesión de fotos estilo revista.", "tips": "Totora es súper fotogénico, vayan en la mañana.", "estimatedTime": "Medio día", "valid_modes": ["pareja", "grupo"], "xpBase": 160, "costLevel": 2, "ubGeo": const GeoPoint(-17.5100, -65.9900)},
      {"number": 37, "title": "Noche de vinos y jazz en Cochabamba", "emoji": "🍷", "category": "Música", "locName": "Zona Norte", "description": "Busquen un bar especializado en vinos bolivianos con música jazz en vivo.", "challenge": "Probar un vino de altura (de Tarija o Cinti).", "tips": "Los vinos bolivianos están ganando premios internacionales.", "estimatedTime": "2 horas", "valid_modes": ["pareja"], "xpBase": 120, "costLevel": 3, "ubGeo": const GeoPoint(-17.3840, -66.1460)},
      {"number": 38, "title": "Preparar juntos silpancho casero", "emoji": "👨‍🍳", "category": "En Casa", "locName": "Hogar", "description": "Compre los ingredientes y cocinen juntos este clásico cochabambino en casa.", "challenge": "Que quede más crujiente que en el restaurante.", "tips": "El secreto es la carne bien finita y el arroz suelto.", "estimatedTime": "2 horas", "valid_modes": ["pareja"], "xpBase": 110, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 39, "title": "Maratón de películas bolivianas", "emoji": "🎬", "category": "En Casa", "locName": "Hogar", "description": "Preparen piqueos y vean 2 o 3 películas hechas en Bolivia.", "challenge": "Ver una película de la que nunca hayan oído hablar.", "tips": "Busquen 'El Presidente del Diablo' o 'Zona Sur'.", "estimatedTime": "4 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 100, "costLevel": 1, "ubGeo": const GeoPoint(0, 0)},
      {"number": 40, "title": "Cata de vinos bolivianos en casa", "emoji": "🧐", "category": "En Casa", "locName": "Hogar", "description": "Compren 3 tipos de vino diferente y hagan su propia cata ciega en casa.", "challenge": "Adivinar cuál es el más caro y cuál el más barato.", "tips": "Sirvan los vinos en copas diferentes para no confundirse.", "estimatedTime": "2 horas", "valid_modes": ["pareja"], "xpBase": 90, "costLevel": 2, "ubGeo": const GeoPoint(0, 0)},
      {"number": 41, "title": "Paseo en kayak en la Angostura", "emoji": "🛶", "category": "Aventura", "locName": "Laguna La Angostura", "description": "Remar juntos en un kayak con el paisaje de los cerros de fondo.", "challenge": "No voltear el kayak (o voltearlo a propósito y reírse).", "tips": "Usen chaleco salvavidas siempre.", "estimatedTime": "3 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 170, "costLevel": 2, "ubGeo": const GeoPoint(-17.4100, -66.2500)},
      {"number": 42, "title": "Tour a Tarata colonial", "emoji": "🏘️", "category": "Escapadas", "locName": "Tarata", "description": "Visiten el pueblo donde nació René Barrientos y caminen por sus calles de cal y canto.", "challenge": "Probar el chicha de maíz tradicional del lugar.", "tips": "Hay buses desde Cochabamba. Lleven sombrero.", "estimatedTime": "Todo el día", "valid_modes": ["pareja", "grupo"], "xpBase": 180, "costLevel": 2, "ubGeo": const GeoPoint(-17.6200, -66.0400)},
      {"number": 43, "title": "Tarde romántica en Villa Tunari", "emoji": "🌴", "category": "Escapadas", "locName": "Villa Tunari", "description": "Viajen al trópico cochabambino a disfrutar del calor, ríos y flora tropical.", "challenge": "Bañarse en el río Chapare.", "tips": "Lleven traje de baño y repelente de mosquitos fuerte.", "estimatedTime": "Fin de semana", "valid_modes": ["pareja"], "xpBase": 190, "costLevel": 3, "ubGeo": const GeoPoint(-16.9700, -65.4300)},
      {"number": 44, "title": "Paseo en bote en la laguna Corani", "emoji": "⛵", "category": "Aventura", "locName": "Laguna Corani", "description": "Aléjense de la ciudad y disfruten del paisaje boscoso y el clima fresco remando.", "challenge": "Remar al compás sin chocar con nada.", "tips": "Lleven abrigo, la laguna es fría.", "estimatedTime": "Medio día", "valid_modes": ["pareja"], "xpBase": 180, "costLevel": 2, "ubGeo": const GeoPoint(-17.2285, -65.8821)},
      {"number": 45, "title": "Tarde de camping en el Parque Tunari", "emoji": "⛺", "category": "Aventura", "locName": "Parque Tunari", "description": "Acampen bajo las estrellas en el parque nacional y hagan una fogata.", "challenge": "Cocinar algo en la fogata.", "tips": "Revisen permisos para acampar y llevar leña seca.", "estimatedTime": "24 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 200, "costLevel": 2, "ubGeo": const GeoPoint(-17.3500, -66.1200)},
      {"number": 46, "title": "Cena con velas en casa con comida cochabambina", "emoji": "🕯️", "category": "Especiales", "locName": "Hogar", "description": "Preparen un ambiente romántico con velas, y cocinen algo típico como pique o chicharrón.", "challenge": "Cenar sin celulares en la mesa.", "tips": "La iluminación lo es todo para el romance.", "estimatedTime": "2.5 horas", "valid_modes": ["pareja"], "xpBase": 120, "costLevel": 2, "ubGeo": const GeoPoint(0, 0)},
      {"number": 47, "title": "Escribir juntos su lista de sueños", "emoji": "📝", "category": "Especiales", "locName": "Un café tranquilo", "description": "Vayan a un café silencioso y escriban 10 cosas que quieren hacer juntos antes de los 50.", "challenge": "Incluir al menos un viaje loco o irreal en la lista.", "tips": "No juzguen las ideas del otro.", "estimatedTime": "2 horas", "valid_modes": ["pareja"], "xpBase": 140, "costLevel": 1, "ubGeo": const GeoPoint(-17.3850, -66.1480)},
      {"number": 48, "title": "Escapada de fin de semana a Aiquile", "emoji": "🎶", "category": "Escapadas", "locName": "Aiquile", "description": "Visiten la capital del charango, un pueblo mágico lleno de música y tradiciones.", "challenge": "Comprar un charango pequeño de recuerdo.", "tips": "Aiquile celebra un festival de charango increíble en noviembre.", "estimatedTime": "Fin de semana", "valid_modes": ["pareja", "grupo"], "xpBase": 190, "costLevel": 3, "ubGeo": const GeoPoint(-18.1800, -65.3700)},
      {"number": 49, "title": "Fogata en un camping con guitarra", "emoji": "🔥", "category": "Aventura", "locName": "Zona Tunari / Liriuni", "description": "La clásica fogata al aire libre con amigos o en pareja, cantando y comiendo marshmallows.", "challenge": "Inventar una historia de terror alrededor de la fogata.", "tips": "Llevar guitarra si alguien sabe tocar.", "estimatedTime": "4 horas", "valid_modes": ["pareja", "grupo"], "xpBase": 160, "costLevel": 2, "ubGeo": const GeoPoint(-17.3100, -66.1500)},
      {"number": 50, "title": "Cena bajo las estrellas en la Angostura", "emoji": "🌌", "category": "Especiales", "locName": "Laguna La Angostura", "description": "El reto final: Preparen una canasta con comida y vayan a cenar de noche viendo las estrellas.", "challenge": "Encontrar una constelación en el cielo.", "tips": "Lleven manta, linterna y buena compañía. ¡Llegaron a la cima de la montaña!", "estimatedTime": "3 horas", "valid_modes": ["pareja"], "xpBase": 250, "costLevel": 3, "ubGeo": const GeoPoint(-17.4100, -66.2500)}
    ];

    // INSERCIÓN MASIVA OPTIMIZADA
    final WriteBatch batch = firestore.batch();
    final CollectionReference adventuresRef = firestore.collection('adventures');

    for (var aventura in aventurasIniciales) {
      // SOLUCIÓN: Usar el número como ID evita duplicados y elimina la necesidad de borrar antes
      DocumentReference docRef = adventuresRef.doc(aventura['number'].toString());
      batch.set(docRef, aventura);
    }

    try {
      await batch.commit();
      debugPrint('✅ 50 Aventuras insertadas exitosamente en Firestore!');
    } catch (e) {
      debugPrint('🔥 Error insertando aventuras: $e');
      rethrow;
    }
  }
}