// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4_VMuDfZ-ityPaqS0oyvest-r8uwZ4Ok',
    appId: '1:716455152061:web:fd5918943352c5c464aad4',
    messagingSenderId: '716455152061',
    projectId: 'datty-app',
    authDomain: 'datty-app.firebaseapp.com',
    storageBucket: 'datty-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoMQzMU9JunESF-hOfMhz0YnZzylZ2bn8',
    appId: '1:716455152061:android:52b83d8cb2f6da8864aad4',
    messagingSenderId: '716455152061',
    projectId: 'datty-app',
    storageBucket: 'datty-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4PbMePRJEpOGT7e9lCQSH245tMF8c1aU',
    appId: '1:716455152061:ios:f74996db7fce037064aad4',
    messagingSenderId: '716455152061',
    projectId: 'datty-app',
    storageBucket: 'datty-app.firebasestorage.app',
    iosBundleId: 'com.example.magicDates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4PbMePRJEpOGT7e9lCQSH245tMF8c1aU',
    appId: '1:716455152061:ios:f74996db7fce037064aad4',
    messagingSenderId: '716455152061',
    projectId: 'datty-app',
    storageBucket: 'datty-app.firebasestorage.app',
    iosBundleId: 'com.example.magicDates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4_VMuDfZ-ityPaqS0oyvest-r8uwZ4Ok',
    appId: '1:716455152061:web:d170b2dc309fc5ef64aad4',
    messagingSenderId: '716455152061',
    projectId: 'datty-app',
    authDomain: 'datty-app.firebaseapp.com',
    storageBucket: 'datty-app.firebasestorage.app',
  );
}
